### PR TITLE
mangle all symbols to be able to co-exist with 1.x

### PR DESCRIPTION
**Pull request by niamster**
```
gsed -i -r 's/ZSTD_/ZSTD_0_5_X_/g' *.c *.go *.h
gsed -i -r 's/package zstd/package zstd_0/g' *.c *.go *.h
gsed -i -r 's/FSE_/FSE_0_5_X_/g' *.c *.go *.h
gsed -i -r 's/HUF_/HUF_0_5_X_/g' *.c *.go *.h
gsed -i -r 's/ZBUFF_/ZBUFF_0_5_X_/g' *.c *.go *.h
gsed -i -r 's/divsufsort\(/divsufsort_0_5_x(/g' *.c *.go *.h
gsed -i -r 's/divbwt\(/divbwt_0_5_x(/g' *.c *.go *.h

... and a few others
```

### CODE REVIEW

**Comment by Viq111** [comment]
I have this ugly process I just used:
```
go test -c # Compile a binary (since it's a lib, cannot compile main so compile tests instead)
go tool nm zstd_0.test > a # Extract all symbols
cat a | cut -d' ' -f4 > b
python a.py > d
cat d | ./a.sh
```

`a.py`:
```python
exclude = ["strings", "_debug", "__cgo_", "_x_cgo"]

with open("b", "r") as f:
	lines = f.readlines()


namespaces = set()
for l in lines:
	skip = False
	for e in exclude:
		if l.startswith(e):
			skip = True
	if "0_5_x" in l.lower(): # Already mangled:
		skip = True
	if skip:
		continue

	n = l.split(".")[0]
	if n == '' or n == '\n':
		continue
	namespaces.add(n)
	if n.startswith("_"):
		namespaces.add(n[1:])

print "".join(str(s) for s in sorted(namespaces))
```

`a.sh`:
```bash
#!/bin/zsh
while read line
do
  #echo "###################\n>>>>> Looking for $line\n#################"
  grep -R zstd_0 -e "$line" > /dev/null && echo "Found reference to $line"
done
```

yields:

```
Found reference to algoTime
Found reference to sqq_table
Found reference to sssort
Found reference to tr_partition
```

So we might want to mangle those additional 4 symbols ?

**Comment by niamster** [comment]
All these symbols are static except `sssort` which is static in 1.x. I'll mangle only `sssort` just to avoid future conflicts.

**Review by Viq111 — APPROVED** [review]

**Comment by Viq111** [comment]
(you might want to add `teams/dev` to https://github.com/DataDog/zstd_0/settings/access so the review counts as "real" reviews)

**Comment by niamster** [comment]
> (you might want to add `teams/dev` to https://github.com/DataDog/zstd_0/settings/access so the review counts as "real" reviews)

Indeed 😆

**Pull request merged**
